backend:
  name: github
  repo: BannerFD/penteract-user-docs

media_folder: static/assets
public_folder: assets

collections:
  - name: faq
    label: Frequently Asked Questions
    folder: doc/faq
    create: true
    extension: md
    fields:
      - { name: title, label: Question }
      - { name: version, label: Version }
      - { name: body, label: Response, widget: markdown }
  - name: howto
    label: How To
    folder: doc/howto
    create: true
    extension: md
    fields:
      - { name: title, label: Title }
      - { name: version, label: Version }
      - { name: path, label: Path }
      - { name: description, label: Description }
      - { name: tags, label: Tags, widget: list }
      - { name: body, label: Instructions, widget: markdown }
