backend:
  name: github
  repo: BannerFD/penteract-user-docs

media_folder: static/assets
public_folder: static/public

collections:
  - name: faq
    label: Frequently Asked Questions
    folder: doc/faq
    create: true
    fields:
      - { name: title, label: Title }
      - { name: version, label: Version }
      - { name: question, label: Question }
      - { name: response, label: Response, widget: markdown }
